/**
 * Driver portraits.
 *
 * Keyed on the exact `drivers.name` values the dataset holds, for the same
 * reason `teamLogo` is: that string is what every payload carries, and a
 * photo is presentation, not data worth a schema migration.
 *
 * All 129 drivers in the dataset have one, so the lookup never misses today.
 * It still returns null for an unknown name rather than guessing a path --
 * a driver added by a later ETL run should get the "to be added" frame, not
 * a broken image.
 *
 * These are third-party images used to identify each driver. Fine for an
 * internal analyst tool; a public deployment would need to clear the rights.
 */
const PORTRAITS: Record<string, string> = {
  "Adrian Sutil": "adrian-sutil",
  "Alex Yoong": "alex-yoong",
  "Alexander Albon": "alexander-albon",
  "Alexander Rossi": "alexander-rossi",
  "Alexander Wurz": "alexander-wurz",
  "Allan McNish": "allan-mcnish",
  "Andrea Kimi Antonelli": "andrea-kimi-antonelli",
  "André Lotterer": "andre-lotterer",
  "Anthony Davidson": "anthony-davidson",
  "Antonio Giovinazzi": "antonio-giovinazzi",
  "Antônio Pizzonia": "antonio-pizzonia",
  "Brendon Hartley": "brendon-hartley",
  "Bruno Senna": "bruno-senna",
  "Carlos Sainz": "carlos-sainz",
  "Charles Leclerc": "charles-leclerc",
  "Charles Pic": "charles-pic",
  "Christian Klien": "christian-klien",
  "Christijan Albers": "christijan-albers",
  "Cristiano da Matta": "cristiano-da-matta",
  "Daniel Ricciardo": "daniel-ricciardo",
  "Daniil Kvyat": "daniil-kvyat",
  "David Coulthard": "david-coulthard",
  "Eddie Irvine": "eddie-irvine",
  "Enrique Bernoldi": "enrique-bernoldi",
  "Esteban Gutiérrez": "esteban-gutierrez",
  "Esteban Ocon": "esteban-ocon",
  "Felipe Massa": "felipe-massa",
  "Felipe Nasr": "felipe-nasr",
  "Fernando Alonso": "fernando-alonso",
  "Franck Montagny": "franck-montagny",
  "Franco Colapinto": "franco-colapinto",
  "Gabriel Bortoleto": "gabriel-bortoleto",
  "Gastón Mazzacane": "gaston-mazzacane",
  "George Russell": "george-russell",
  "Giancarlo Fisichella": "giancarlo-fisichella",
  "Gianmaria Bruni": "gianmaria-bruni",
  "Giedo van der Garde": "giedo-van-der-garde",
  "Giorgio Pantano": "giorgio-pantano",
  "Guanyu Zhou": "guanyu-zhou",
  "Heikki Kovalainen": "heikki-kovalainen",
  "Heinz-Harald Frentzen": "heinz-harald-frentzen",
  "Isack Hadjar": "isack-hadjar",
  "Jack Aitken": "jack-aitken",
  "Jack Doohan": "jack-doohan",
  "Jacques Villeneuve": "jacques-villeneuve",
  "Jaime Alguersuari": "jaime-alguersuari",
  "Jarno Trulli": "jarno-trulli",
  "Jean Alesi": "jean-alesi",
  "Jean-Éric Vergne": "jean-eric-vergne",
  "Jenson Button": "jenson-button",
  "Johnny Herbert": "johnny-herbert",
  "Jolyon Palmer": "jolyon-palmer",
  "Jos Verstappen": "jos-verstappen",
  "Juan Pablo Montoya": "juan-pablo-montoya",
  "Jules Bianchi": "jules-bianchi",
  "Justin Wilson": "justin-wilson",
  "Jérôme d'Ambrosio": "jerome-d-ambrosio",
  "Kamui Kobayashi": "kamui-kobayashi",
  "Karun Chandhok": "karun-chandhok",
  "Kazuki Nakajima": "kazuki-nakajima",
  "Kevin Magnussen": "kevin-magnussen",
  "Kimi Räikkönen": "kimi-raikkonen",
  "Lance Stroll": "lance-stroll",
  "Lando Norris": "lando-norris",
  "Lewis Hamilton": "lewis-hamilton",
  "Liam Lawson": "liam-lawson",
  "Logan Sargeant": "logan-sargeant",
  "Luca Badoer": "luca-badoer",
  "Lucas di Grassi": "lucas-di-grassi",
  "Luciano Burti": "luciano-burti",
  "Marc Gené": "marc-gene",
  "Marcus Ericsson": "marcus-ericsson",
  "Mark Webber": "mark-webber",
  "Markus Winkelhock": "markus-winkelhock",
  "Max Chilton": "max-chilton",
  "Max Verstappen": "max-verstappen",
  "Michael Schumacher": "michael-schumacher",
  "Mick Schumacher": "mick-schumacher",
  "Mika Häkkinen": "mika-hakkinen",
  "Mika Salo": "mika-salo",
  "Narain Karthikeyan": "narain-karthikeyan",
  "Nelson Piquet Jr.": "nelson-piquet-jr",
  "Nicholas Latifi": "nicholas-latifi",
  "Nick Heidfeld": "nick-heidfeld",
  "Nico Hülkenberg": "nico-hulkenberg",
  "Nico Rosberg": "nico-rosberg",
  "Nicolas Kiesa": "nicolas-kiesa",
  "Nikita Mazepin": "nikita-mazepin",
  "Nyck de Vries": "nyck-de-vries",
  "Oliver Bearman": "oliver-bearman",
  "Olivier Panis": "olivier-panis",
  "Oscar Piastri": "oscar-piastri",
  "Pascal Wehrlein": "pascal-wehrlein",
  "Pastor Maldonado": "pastor-maldonado",
  "Patrick Friesacher": "patrick-friesacher",
  "Paul di Resta": "paul-di-resta",
  "Pedro Diniz": "pedro-diniz",
  "Pedro de la Rosa": "pedro-de-la-rosa",
  "Pierre Gasly": "pierre-gasly",
  "Pietro Fittipaldi": "pietro-fittipaldi",
  "Ralf Schumacher": "ralf-schumacher",
  "Ralph Firman": "ralph-firman",
  "Ricardo Zonta": "ricardo-zonta",
  "Rio Haryanto": "rio-haryanto",
  "Robert Doornbos": "robert-doornbos",
  "Robert Kubica": "robert-kubica",
  "Roberto Merhi": "roberto-merhi",
  "Romain Grosjean": "romain-grosjean",
  "Rubens Barrichello": "rubens-barrichello",
  "Sakon Yamamoto": "sakon-yamamoto",
  "Scott Speed": "scott-speed",
  "Sebastian Vettel": "sebastian-vettel",
  "Sergey Sirotkin": "sergey-sirotkin",
  "Sergio Pérez": "sergio-perez",
  "Stoffel Vandoorne": "stoffel-vandoorne",
  "Sébastien Bourdais": "sebastien-bourdais",
  "Sébastien Buemi": "sebastien-buemi",
  "Takuma Sato": "takuma-sato",
  "Tarso Marques": "tarso-marques",
  "Tiago Monteiro": "tiago-monteiro",
  "Timo Glock": "timo-glock",
  "Tomáš Enge": "tomas-enge",
  "Valtteri Bottas": "valtteri-bottas",
  "Vitaly Petrov": "vitaly-petrov",
  "Vitantonio Liuzzi": "vitantonio-liuzzi",
  "Will Stevens": "will-stevens",
  "Yuji Ide": "yuji-ide",
  "Yuki Tsunoda": "yuki-tsunoda",
  "Zsolt Baumgartner": "zsolt-baumgartner",
};

/** Public path to a driver's portrait, or null when none ships for them. */
export function driverPhoto(name: string): string | null {
  const slug = PORTRAITS[name];
  return slug ? `/drivers/${slug}.webp` : null;
}
